apiVersion: v1
kind: Pod
metadata:
  name: rockerito # Nombre del pod (cada uno elige lo que quiere)
  namespace: rock # Nombre del namespace (Valores aceptados: techno, salsa, reggaeton, rock, pop)
  annotations:
    student: "Juan Camilo Valencia" # Nombre del estudiante que crea el pod
    student_code: "2259459" # Código del estudiante que crea el pod
    music-preference: "rock" # Género musical preferido (cada uno elige el que quiere)
spec:
  containers:
    - name: rockero # Nombre del contenedor (cada uno elige lo que quiere)
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica" # Valor del taint (Valores aceptados: perreo-intenso, guitarra-electrica, bass-boost, sabor-latino, pop)
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - metalero # Estilo musical del nodo (Valores posibles: urbano, metalero, electronico, latino, pop)
