apiVersion: v1
kind: Pod
metadata:
  name: salsa-romantica # Nombre del pod (cada uno elige lo que quiere)
  namespace: salsa # Nombre del namespace (Valores aceptados: techno, salsa, reggaeton, rock, pop)
  annotations:
    student: "Juan Sebastian Miller" # Nombre del estudiante que crea el pod
    student_code: "2324115" # Código del estudiante que crea el pod
    music-preference: "salsa" # Género musical preferido (cada uno elige el que quiere)
spec:
  containers:
    - name: romantiqueo # Nombre del contenedor (cada uno elige lo que quiere)
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "sabor-latino" # Valor del taint (Valores aceptados: perreo-intenso, guitarra-electrica, bass-boost, sabor-latino, pop)
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - latino # Estilo musical del nodo (Valores posibles: urbano, metalero, electronico, latino, pop)
