apiVersion: v1
kind: Pod
metadata:
  name: Anime # Nombre del pod (cada uno elige lo que quiere)
  namespace: j-pop # Nombre del namespace (cada uno elige el que quiere, debe coincidir con el nombre del archivo)
  annotations:
    student: "Luis Carabali Rivera" # Nombre del estudiante que crea el pod
    student_code: "2410006" # Código del estudiante que crea el pod
    music-preference: "j-pop" # Género musical preferido (cada uno elige el que quiere)
spec:
  containers:
    - name: Anime # Nombre del contenedor (cada uno elige lo que quiere)
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica" # Valor del taint (mirar el valor del nodo con la música de su preferencia)
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - pop # Estilo musical del nodo (mirar en nodes/labels.yaml el estilo del nodo con la música de su preferencia)
