apiVersion: v1
kind: Pod
metadata:
  name: johntechno 
  namespace: techno 
  annotations:
    student: "John Lourido" 
    student_code: "1124153" 
    music-preference: "techno" # Género musical preferido (cada uno elige el que quiere)
spec:
  containers:
    - name: johntechno-container # Nombre del contenedor (cada uno elige lo que quiere)
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost" 
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico 